"""QR session markers: attributing SD-card footage to an instructor.

A card knows only the camera and the clock — not whose jump it filmed. In the
SD-card flow the instructor films a short clip of their printed QR code (payload
``skydiveos-staff:<staffs._id>``, generated by ``scripts/make_instructor_qr.py``)
**once per recording session — at the start, at the end, or anywhere in between**.
The marker clip itself never becomes a job. The QR replaces only the *staff lookup*
(``staffs.goproSerial``): which specific jump/customer/role a clip belongs to is
still decided per clip by ``captured_at`` + the load window
(:meth:`ingest.match.FootageMatcher.resolve_for_staff`).

**Marker position is not a protocol.** An instructor who lands, packs, and films
their card at the *end* of the day must get the same attribution as one who films
it before the first jump — asking a working jumper to remember "scan first, always"
is how footage ends up unattributed. So the index is *card-level*, not a
sequential walk:

* One staff id among a day's markers (by far the common case — one card, one
  jumper) → **every** clip of that day belongs to that staff, whatever side of the
  marker it sits on. Position is irrelevant, and a second scan of the same card
  changes nothing.
* Two or more staff ids (a camera handed over mid-day) → the marker's *side* does
  carry information, and it is inferred once per card from the layout: clips before
  the first marker but none after the last means the markers trail their sessions
  (:data:`TRAILING`); clips after the last marker but none before the first means
  they lead (:data:`LEADING`). A layout that supports neither reading is genuinely
  ambiguous — it is logged as such and falls back to :data:`LEADING`, the
  historical rule.

Because the answer depends on the whole card, the hand-off cannot run per clip as
it lands: :class:`ingest.discovery.CameraDiscoveryService` holds a card's
notifications until that card's pull has finished, so a marker filmed last is
already staged when attribution runs.

Pieces:

* :func:`decode_staff_qr` — sample the head of a clip with ffmpeg (native
  resolution — QR decoding needs the pixels) and decode with OpenCV.
* :func:`cached_staff_qr` — the same, cached in a ``<stem>.qr.json`` sidecar
  next to the staged clip (positive AND negative results), with a duration gate
  so a 20-minute jump is never probed — a deliberate marker clip is seconds long.
* :class:`QrSessionIndex` / :func:`build_session_index` — order one staging-day
  directory's clips by capture time (from their ``.ingest.json`` manifests) and
  map each clip to the session that governs it.
* :func:`qr_identity_resolver` — the adapter :class:`ingest.discovery.
  CameraDiscoveryService` consumes per clip (its ``identity_resolver`` seam).

Like :mod:`ingest.match`, this module must stay free of ``api.*`` imports.
``cv2``/``numpy`` are imported lazily inside the decode path with an actionable
error, so the rest of /ingest imports without the CV stack.
"""

from __future__ import annotations

import json
import logging
import subprocess
import time
from collections.abc import Callable, Iterable
from dataclasses import dataclass
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

#: Only QR payloads with this prefix identify an instructor — a boarding pass or
#: sticker that happens to be in frame is ignored.
QR_STAFF_PREFIX = "skydiveos-staff:"

#: Sidecar caching a clip's decode result, next to the staged MP4.
QR_SIDECAR_SUFFIX = ".qr.json"

#: Marker direction on a multi-staff card: the marker was filmed at the START of its
#: session (clips FOLLOW it — the historical rule) …
LEADING = "leading"
#: … or at the END of it (clips PRECEDE it). Inferred per card, never configured.
TRAILING = "trailing"

#: Cap on each ffprobe/ffmpeg subprocess — a wedged tool must not stall ingest.
_SUBPROCESS_TIMEOUT_S = 60.0


@dataclass(frozen=True)
class ClipIdentity:
    """Who a staged clip belongs to, as far as the QR session flow can tell."""

    staff_id: str | None  #: SkydiveOS ``staffs._id`` from the governing marker, or None
    is_qr_marker: bool = False  #: True → this clip IS a session marker (never a job)
    role: str | None = None  #: load-derived role for THIS clip, when resolvable


#: Resolves a pulled clip's identity: ``(camera_id, mp4_path) -> ClipIdentity | None``.
#: ``None`` means "no opinion — behave exactly as before" (registry hint, serial match).
IdentityResolver = Callable[[str, str], "ClipIdentity | None"]


def parse_staff_payload(payload: str | None) -> str | None:
    """The staff id inside a decoded QR payload, or ``None`` if it isn't ours."""
    if not payload or not payload.startswith(QR_STAFF_PREFIX):
        return None
    staff_id = payload[len(QR_STAFF_PREFIX):].strip()
    return staff_id or None


# --------------------------------------------------------------------------- #
# Decoding
# --------------------------------------------------------------------------- #


def _probe_video(mp4_path: str | Path) -> tuple[float | None, int | None, int | None]:
    """Best-effort ``(duration_s, width, height)`` for a video file. Never raises."""
    try:
        out = subprocess.run(
            [
                "ffprobe", "-v", "error",
                "-select_streams", "v:0",
                "-show_entries", "stream=width,height:format=duration",
                "-of", "json", str(mp4_path),
            ],
            capture_output=True, text=True, timeout=_SUBPROCESS_TIMEOUT_S, check=False,
        )
        data = json.loads(out.stdout or "{}")
        streams = data.get("streams") or [{}]
        duration_raw = (data.get("format") or {}).get("duration")
        duration = float(duration_raw) if duration_raw is not None else None
        return duration, streams[0].get("width"), streams[0].get("height")
    except Exception as e:  # noqa: BLE001 - a bad file yields "unknown", not a crash
        logger.debug("ffprobe failed for %s: %r", mp4_path, e)
        return None, None, None


def _load_detectors() -> list[Any]:
    """QR detectors, best first. Raises an actionable error when OpenCV is absent."""
    try:
        import cv2
    except ImportError as e:  # pragma: no cover - environment-dependent
        raise RuntimeError(
            f"opencv-python is required for QR session markers but failed to import: {e!r}"
        ) from e

    detectors: list[Any] = []
    aruco = getattr(cv2, "QRCodeDetectorAruco", None)
    if aruco is not None:
        detectors.append(aruco())
    detectors.append(cv2.QRCodeDetector())
    return detectors


#: Barrel-distortion coefficients tried per frame when the flat decode fails.
#: A GoPro's wide FOV bows the code enough that OpenCV *locates* it but mis-samples
#: the modules (verified on real handcam footage: flat decode failed on every frame,
#: k1=-0.25 read it cleanly). Zero must stay first — the fast path for a flat,
#: printed code or a camera in Linear lens mode.
_UNDISTORT_K1_SWEEP: tuple[float, ...] = (0.0, -0.18, -0.25, -0.32)


def _decode_qr_frame(gray: Any, detectors: list[Any]) -> str | None:
    """Decode one grayscale frame, sweeping fisheye undistortion. Never raises."""
    import cv2
    import numpy as np

    h, w = gray.shape[:2]
    camera = np.array([[w * 0.7, 0, w / 2], [0, w * 0.7, h / 2], [0, 0, 1]], np.float64)
    for k1 in _UNDISTORT_K1_SWEEP:
        candidate = gray if k1 == 0.0 else cv2.undistort(
            gray, camera, np.array([k1, 0.0, 0.0, 0.0], np.float64)
        )
        if max(h, w) > 2000:  # decoders sample better below ~2k on big frames
            candidate = cv2.resize(candidate, None, fx=0.5, fy=0.5, interpolation=cv2.INTER_AREA)
        for detector in detectors:
            try:
                payload, _points, _straight = detector.detectAndDecode(candidate)
            except Exception:  # noqa: BLE001 - a detector crash on one frame is not fatal
                continue
            staff_id = parse_staff_payload(payload)
            if staff_id is not None:
                return staff_id
    return None


def decode_staff_qr(
    mp4_path: str | Path,
    *,
    scan_seconds: float = 8.0,
    fps: float = 2.0,
) -> str | None:
    """Decode a staff QR from the head of a clip, or ``None``.

    Samples ``fps`` frames/second from the first ``scan_seconds`` at the clip's
    native resolution (downscaling first destroys the code — this is why
    ``analysis.extract`` isn't reused: it targets proxies and shrinks frames).
    Frames stream through one at a time (a 4K rgb24 frame is ~24 MB; never
    buffer the lot); each is tried flat and through the fisheye undistortion
    sweep (:data:`_UNDISTORT_K1_SWEEP` — a GoPro's wide lens bows the code past
    what a flat decode tolerates). First payload carrying
    :data:`QR_STAFF_PREFIX` wins. Never raises for a bad file — that's just
    "no QR here".
    """
    import cv2
    import numpy as np

    detectors = _load_detectors()
    _, width, height = _probe_video(mp4_path)
    if not width or not height:
        return None
    frame_bytes = width * height * 3

    proc = subprocess.Popen(
        [
            "ffmpeg", "-v", "error",
            "-t", f"{scan_seconds:.3f}",
            "-i", str(mp4_path),
            "-vf", f"fps={fps:g}",
            "-pix_fmt", "rgb24", "-f", "rawvideo", "pipe:1",
        ],
        stdout=subprocess.PIPE,
        stderr=subprocess.DEVNULL,
    )
    try:
        assert proc.stdout is not None
        while True:
            chunk = proc.stdout.read(frame_bytes)
            if len(chunk) < frame_bytes:
                return None
            frame = np.frombuffer(chunk, dtype=np.uint8).reshape(height, width, 3)
            gray = cv2.cvtColor(frame, cv2.COLOR_RGB2GRAY)
            staff_id = _decode_qr_frame(gray, detectors)
            if staff_id is not None:
                logger.info("QR session marker in %s -> staff %s", mp4_path, staff_id)
                return staff_id
    finally:
        proc.kill()
        proc.wait(timeout=_SUBPROCESS_TIMEOUT_S)


def _sidecar_path(mp4_path: Path) -> Path:
    return mp4_path.with_suffix(QR_SIDECAR_SUFFIX)


def cached_staff_qr(
    mp4_path: Path,
    *,
    max_clip_seconds: float = 60.0,
    scan_seconds: float = 8.0,
) -> str | None:
    """:func:`decode_staff_qr` with a duration gate and a sidecar cache.

    Only clips shorter than ``max_clip_seconds`` are probed — a deliberate
    marker clip is seconds long, and this keeps 20-minute jumps out of the
    decoder. Both outcomes are cached in ``<stem>.qr.json`` so a clip is
    decoded at most once ever, no matter how many scans revisit the folder.
    """
    sidecar = _sidecar_path(mp4_path)
    if sidecar.exists():
        try:
            cached = json.loads(sidecar.read_text())
            staff_id = cached.get("staff_id")
            return staff_id if isinstance(staff_id, str) else None
        except (ValueError, OSError):
            logger.warning("unreadable QR sidecar %s; re-decoding", sidecar)

    duration, _w, _h = _probe_video(mp4_path)
    result: dict[str, Any] = {"staff_id": None, "skipped": None, "decoded_at": time.time()}
    if duration is not None and duration > max_clip_seconds:
        result["skipped"] = "too-long"
    else:
        result["staff_id"] = decode_staff_qr(mp4_path, scan_seconds=scan_seconds)

    try:
        sidecar.write_text(json.dumps(result, indent=2) + "\n")
    except OSError as e:
        logger.warning("could not write QR sidecar %s: %r", sidecar, e)
    staff_id = result["staff_id"]
    return staff_id if isinstance(staff_id, str) else None


# --------------------------------------------------------------------------- #
# Session attribution
# --------------------------------------------------------------------------- #


_MANIFEST_SUFFIX = ".ingest.json"  # written by ingest.pull for every staged clip


@dataclass(frozen=True)
class _Marker:
    epoch: float
    filename: str
    staff_id: str


class QrSessionIndex:
    """Session map for one staging-day directory — a card-level view, not a walk.

    Attribution is deliberately **position-agnostic** for the common single-staff
    card: one staff id among the day's markers means every clip of that day is that
    staff's, whether the marker was filmed before the first jump, after the last, or
    halfway through. Only a card carrying *two or more* staff sessions needs to know
    which side of a marker its clips sit on, and that direction is inferred once from
    the card's layout (:meth:`_infer_direction`) rather than mandated as a filming
    protocol. A clip no marker can claim still gets ``staff_id=None``, and downstream
    falls back to the serial-based match exactly as before.
    """

    def __init__(self, epochs: dict[str, float], markers: list[_Marker]) -> None:
        self._epochs = epochs  # filename -> created_epoch
        self._markers = sorted(markers, key=lambda m: m.epoch)
        self._marker_files = {m.filename for m in self._markers}
        self._staff_markers = list(self._markers)
        staff_ids = {m.staff_id for m in self._staff_markers}
        #: Set when the whole day carries ONE staff: attribution ignores position.
        self._sole_staff = staff_ids.pop() if len(staff_ids) == 1 else None
        self._direction = LEADING if self._sole_staff else self._infer_direction()

    @classmethod
    def from_clips(
        cls, rows: Iterable[tuple[str, float, str | None]]
    ) -> QrSessionIndex:
        """Build an index from decoded ``(filename, epoch, staff_id)`` rows.

        For a caller that already has the decode results in hand — the card probe
        (``scripts/check_sdcard.py``) reads straight off the mount, where there are no
        ``.ingest.json`` manifests to walk — so a diagnostic reports the same
        attribution the pipeline will make, instead of re-implementing it.
        """
        epochs: dict[str, float] = {}
        markers: list[_Marker] = []
        for filename, epoch, staff_id in rows:
            epochs[filename] = float(epoch)
            if staff_id is not None:
                markers.append(
                    _Marker(epoch=float(epoch), filename=filename, staff_id=staff_id)
                )
        return cls(epochs, markers)

    @property
    def direction(self) -> str:
        """:data:`LEADING` / :data:`TRAILING` — which side of its clips a marker sits on."""
        return self._direction

    def _clip_epochs(self) -> list[float]:
        return [
            epoch for name, epoch in self._epochs.items() if name not in self._marker_files
        ]

    def _infer_direction(self) -> str:
        """Which side of its session each staff marker sits on, read off the layout.

        Only reached for a card with two or more staff sessions, where the side is the
        only thing separating them. Clips *before* the first marker with none after the
        last can only be markers that trail their sessions; clips after the last with
        none before the first can only be markers that lead. Anything else (clips on
        both outer edges, or on neither) reads equally well both ways — that is logged
        and falls back to :data:`LEADING`, the historical rule, rather than silently
        re-attributing footage a previously-working card already delivered.
        """
        if not self._staff_markers:
            return LEADING
        clips = self._clip_epochs()
        head = any(e < self._staff_markers[0].epoch for e in clips)
        tail = any(e > self._staff_markers[-1].epoch for e in clips)
        if head and not tail:
            logger.info(
                "card holds %d staff sessions and every clip precedes a marker: "
                "reading markers as END-of-session", len(self._staff_markers),
            )
            return TRAILING
        if not tail or head:
            logger.warning(
                "card holds %d staff sessions (%s) in a layout that reads both ways; "
                "attributing clips to the PRECEDING marker. Film one marker per "
                "session, consistently at the start or at the end of it.",
                len(self._staff_markers),
                ", ".join(sorted({m.staff_id or "?" for m in self._staff_markers})),
            )
        return LEADING

    def _staff_at(self, epoch: float) -> str | None:
        """The staff member governing a capture instant, or ``None`` if unclaimed."""
        if self._sole_staff is not None:
            return self._sole_staff
        if self._direction == TRAILING:
            return next(
                (m.staff_id for m in self._staff_markers if m.epoch >= epoch), None
            )
        staff: str | None = None
        for marker in self._staff_markers:
            if marker.epoch > epoch:
                break
            staff = marker.staff_id
        return staff

    def identity_for(self, mp4_path: str | Path) -> ClipIdentity:
        path = Path(mp4_path)
        if path.name in self._marker_files:
            marker = next(m for m in self._markers if m.filename == path.name)
            return ClipIdentity(staff_id=marker.staff_id, is_qr_marker=True)

        epoch = self._epochs.get(path.name)
        if epoch is None:
            try:
                epoch = path.stat().st_mtime
            except OSError:
                return ClipIdentity(staff_id=None)

        return ClipIdentity(staff_id=self._staff_at(epoch))


def build_session_index(
    day_dir: Path,
    *,
    max_clip_seconds: float = 60.0,
    scan_seconds: float = 8.0,
) -> QrSessionIndex:
    """Index one staging-day directory (``.../_camera-staging/<id>/<date>``).

    Capture order comes from each clip's ``.ingest.json`` manifest
    (``created_epoch``); QR decodes go through the sidecar cache, so rebuilding
    the index per lookup costs a directory read, not a video decode.
    """
    epochs: dict[str, float] = {}
    markers: list[_Marker] = []
    for manifest_path in sorted(day_dir.glob(f"*{_MANIFEST_SUFFIX}")):
        try:
            manifest = json.loads(manifest_path.read_text())
        except (ValueError, OSError) as e:
            logger.warning("unreadable ingest manifest %s: %r", manifest_path, e)
            continue
        mp4 = Path(str((manifest.get("files") or {}).get("mp4") or ""))
        if not mp4.name:
            continue
        epoch = manifest.get("created_epoch")
        if not isinstance(epoch, (int, float)):
            try:
                epoch = (day_dir / mp4.name).stat().st_mtime
            except OSError:
                continue
        epochs[mp4.name] = float(epoch)
        staff_id = cached_staff_qr(
            day_dir / mp4.name,
            max_clip_seconds=max_clip_seconds,
            scan_seconds=scan_seconds,
        )
        if staff_id is not None:
            markers.append(_Marker(epoch=float(epoch), filename=mp4.name, staff_id=staff_id))
    return QrSessionIndex(epochs, markers)


def qr_identity_resolver(
    matcher: Any | None = None,
    *,
    clock_tz: str | None = None,
    max_clip_seconds: float = 60.0,
    scan_seconds: float = 8.0,
) -> IdentityResolver:
    """The per-clip identity resolver discovery consumes in SD-card mode.

    Builds the session index from the clip's own staging directory (cheap — the
    sidecars are the cache), and, when a :class:`~ingest.match.FootageMatcher`
    is wired, fills the clip's load-derived role via ``resolve_for_staff``.
    Never raises and never blocks a hand-off: an unresolvable clip comes back
    with ``staff_id=None`` / ``role=None`` and the caller falls back exactly as
    it would without a resolver.
    """

    def _resolve(camera_id: str, mp4_path: str) -> ClipIdentity | None:
        try:
            index = build_session_index(
                Path(mp4_path).parent,
                max_clip_seconds=max_clip_seconds,
                scan_seconds=scan_seconds,
            )
            identity = index.identity_for(mp4_path)
        except Exception as e:  # noqa: BLE001 - attribution must never break the hand-off
            logger.exception("QR session attribution failed for %s: %r", mp4_path, e)
            return None

        if identity.is_qr_marker or identity.staff_id is None or matcher is None:
            return identity

        # Which jump (and therefore which role) is still per clip, from the load.
        from .discovery import _probe_capture_time  # noqa: PLC0415 - avoids a module cycle
        from .match import FootageMatchError

        captured_at = _probe_capture_time(mp4_path, clock_tz=clock_tz)
        if captured_at is None:
            return identity
        try:
            role = matcher.resolve_for_staff(identity.staff_id, captured_at).role
        except FootageMatchError as e:
            logger.warning(
                "load match for QR staff %s failed (%r); clip %s keeps no role",
                identity.staff_id, e, mp4_path,
            )
            return identity
        return ClipIdentity(staff_id=identity.staff_id, role=role)

    return _resolve
